-- RENOVA INSPECTOR — migración histórica alternativa, deliberadamente sin-op.
--
-- El modelo canónico de inspecciones se crea en
-- 20260706120000_demo_vertical_slice.sql y es el que consumen las vistas,
-- RPCs, RLS y pruebas posteriores (`inspections.unit_id/inspected_on`,
-- `inspection_measurements`).
--
-- La versión original de este archivo intentaba crear otro modelo incompatible
-- (`vehicles`, `inspections.vehicle_id/inspection_date` e
-- `inspection_items`). Su propio encabezado documentaba que ambos modelos no
-- podían ejecutarse juntos; en un replay limpio el modelo canónico ya existe,
-- por lo que el archivo original rompía en `inspections_plate_date_idx`.
--
-- Se conserva el archivo y su timestamp histórico, pero no se vuelve a crear
-- el modelo alternativo ni se toca ningún dato. El contrato activo queda
-- definido por las migraciones canónicas anteriores y posteriores.

-- Intencionalmente vacío.
