// Entire CLI extension for Pi
// Auto-generated by `entire enable --agent pi`
// Do not edit manually — changes will be overwritten on next install.
//
// Forwards Pi lifecycle events to `entire hooks pi <event>` so Entire can
// create checkpoints, capture transcripts, and offer rewind/resume.
//
// ENTIRE_CMD is replaced at install time by Entire's installer.

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { execFile } from "node:child_process";

export default function (pi: ExtensionAPI) {
  // A Pi subagent is a nested `pi` process (subagent extensions spawn one per task
  // with cwd inside the project, where Pi auto-discovers this same project-local
  // extension), so it would otherwise forward its own lifecycle as the user's
  // session. Mark this process so any Pi it spawns knows it is nested.
  //
  // WARNING: Entire's own hook subprocesses inherit this marker from the parent, so
  // the CLI side must never treat it as a skip signal — it would disable tracking
  // for everyone. See docs/architecture/agent-guide.md.
  const nested = Boolean(process.env.ENTIRE_PI_NESTED);
  process.env.ENTIRE_PI_NESTED = "1";

  const ENTIRE_CMD = 'entire';
  let pendingSkillEvents: Array<{ skill_name: string; invocation: string; timestamp: string }> = [];

  // fireHook pipes data to `entire hooks pi <hookName>` and resolves with the
  // hook's stdout (empty string on any failure). Most hooks ignore the return;
  // before_agent_start uses it to apply a model-context injection.
  function fireHook(hookName: string, data: Record<string, unknown>): Promise<string> {
    return new Promise((resolve) => {
      try {
        const child = execFile(
          "sh",
          ["-c", `${ENTIRE_CMD} hooks pi ${hookName}`],
          { timeout: 10000, windowsHide: true, maxBuffer: 4 * 1024 * 1024 },
          (_err, stdout) => resolve(typeof stdout === "string" ? stdout : ""),
        );
        child.stdin?.end(JSON.stringify(data));
      } catch {
        // best effort — never block the agent on a hook failure
        resolve("");
      }
    });
  }

  // parseInjectedContext scans a hook's stdout for Entire's injection envelope
  // ({"inject_context":"..."}) and returns the text to inject, or null.
  function parseInjectedContext(stdout: string): string | null {
    if (!stdout) return null;
    for (const line of stdout.split("\n")) {
      const trimmed = line.trim();
      if (!trimmed.startsWith("{")) continue;
      try {
        const parsed = JSON.parse(trimmed) as { inject_context?: unknown };
        if (typeof parsed.inject_context === "string" && parsed.inject_context.length > 0) {
          return parsed.inject_context;
        }
      } catch {
        // not our envelope — ignore
      }
    }
    return null;
  }

  function parseSkillInvocation(text: string): { skill_name: string; invocation: string } | null {
    const match = text.trimStart().match(/^\/skill:([a-z0-9][a-z0-9-]{0,63})(?:\s|$)/);
    if (!match) return null;
    const invocation = text.trimStart().split(/\s+/, 1)[0] ?? `/skill:${match[1]}`;
    return { skill_name: match[1], invocation };
  }

  // Agent-driven bash subprocesses inherit a real TTY but cannot answer
  // hook prompts. Disable git/Entire terminal prompts for bash calls so
  // Entire treats agent-driven commits as non-interactive.
  //
  // Registered even when nested: a nested Pi is non-interactive by construction
  // while still inheriting the parent's TTY, and Entire's git hooks live in
  // .git/hooks independently of this extension, so a nested subagent that commits
  // needs this hardening at least as much as the parent does.
  pi.on("tool_call", async (event) => {
    if (event.toolName !== "bash") return;
    const input = event.input as { command?: string };
    if (typeof input.command !== "string" || input.command.includes("GIT_TERMINAL_PROMPT=")) {
      return;
    }
    input.command = "export GIT_TERMINAL_PROMPT=0\n" + input.command;
  });

  // Everything below forwards session lifecycle to Entire, which only the
  // top-level Pi may do.
  if (nested) return;

  pi.on("input", async (event) => {
    const skill = parseSkillInvocation(event.text);
    if (skill) {
      pendingSkillEvents.push({ ...skill, timestamp: new Date().toISOString() });
    }
    return { action: "continue" };
  });

  pi.on("session_start", async (_event, ctx) => {
    await fireHook("session_start", {
      type: "session_start",
      cwd: ctx.cwd,
      session_file: ctx.sessionManager.getSessionFile(),
    });
  });

  pi.on("before_agent_start", async (event, ctx) => {
    const skillEvents = pendingSkillEvents;
    pendingSkillEvents = [];
    const stdout = await fireHook("before_agent_start", {
      type: "before_agent_start",
      cwd: ctx.cwd,
      session_file: ctx.sessionManager.getSessionFile(),
      prompt: event.prompt,
      skill_events: skillEvents,
    });
    const injected = parseInjectedContext(stdout);
    if (injected) {
      // Inject a hidden, persistent message so the model learns about Entire.
      // display:false keeps it out of the user-facing transcript while still
      // sending it to the LLM. Entire emits this at most once per session.
      return {
        message: {
          customType: "entire-context",
          content: injected,
          display: false,
        },
      };
    }
  });

  pi.on("agent_end", async (_event, ctx) => {
    await fireHook("agent_end", {
      type: "agent_end",
      cwd: ctx.cwd,
      session_file: ctx.sessionManager.getSessionFile(),
    });
  });

  pi.on("session_shutdown", async () => {
    await fireHook("session_shutdown", { type: "session_shutdown" });
  });
}
